-- Habilita la creación de usuarios en Oracle 12c/19c/21c/23c
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Crear el usuario
CREATE USER yona_des IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- Asignar cuota y permisos básicos
ALTER USER yona_des QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO yona_des;
GRANT "RESOURCE" TO yona_des;
ALTER USER yona_des DEFAULT ROLE "RESOURCE";